---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sig-storage-local-static-provisioner
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/sig-storage-local-static-provisioner

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-static-provisioner
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: local-static-provisioner
#      version: '6.5.*'
      sourceRef:
        kind: HelmRepository
        name: sig-storage-local-static-provisioner
      interval: 5m
  releaseName: local-static-provisioner

#  serviceAccountName: kustomize-controller
  valuesFrom:
    - kind: ConfigMap
      name: local-storage-config
      optional: true
