---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: load-balancer
spec:
  addresses: #[]
    - 10.20.30.207/32

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: load-balancer
spec:
  ipAddressPools:
    - load-balancer
