---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podinfo.yaml
#components:
#  - "../../_components/namespace"

#patches:
#  - target:
#      group: autoscaling
#      version: v2
#      name: podinfo
#      namespace: podinfo
#      kind: HorizontalPodAutoscaler
#    patch: |-
#      apiVersion: autoscaling/v2
#      kind: HorizontalPodAutoscaler
#      metadata:
#        name: podinfo
#      spec:
#        minReplicas: 3