---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../_base
resources:
  - metallb.yaml
  - storage-config.yaml
  - storage.yaml

#patches:
patchesJson6902:
  - target:
      version: v1beta1
      group: metallb.io
      kind: IPAddressPool
      name: exampless
      namespace: metallb-system
    patch: |-
      - op: replace
        path: /spec/addresses
        value:
          - 10.10.10.27/32
          - 10.10.10.28/32
          - 10.10.10.29/32
