---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../_base
resources:
  - cluster-vars.yaml
  - metallb.yaml
  - storage-config.yaml
  - cert-issuer.yaml
  - storage.yaml
  - podinfo.yaml
