---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../_base
resources:
  - metallb.yaml
  - storage-config.yaml
  - storage.yaml
  - podinfo.yaml

patches:
  - target:
      kind: Kustomization
      name: ${pool_name}
    patch: |-
      kind: Kustomization
      metadata:
        name: _
      spec:
        patches:
          - target:
              kind: IPAddressPool
            patch: |-
              apiVersion: metallb.io/v1beta1
              kind: IPAddressPool
              metadata:
                name: _
              spec:
                avoidBuggyIPs: true
                addresses:
                  - 10.10.10.207/32
                  - 10.10.10.208/32

#patches:
#patchesJson6902:
#  - target:
#      version: v1beta1
#      group: metallb.io
#      kind: IPAddressPool
#      name: exampless
#      namespace: metallb-system
#    patch: |-
#      - op: replace
#        path: /spec/addresses
#        value:
#          - 10.10.10.27/32
#          - 10.10.10.28/32
#          - 10.10.10.29/32
