---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-app
  namespace: flux-system
spec:
  dependsOn:
    - name: gateway-api
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
#  serviceAccountName: kustomize-controller
  path: ./apps/podinfo
  prune: false
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: podinfo
      gateway_name: frontend
      gateway_namespace: networking


#  patches:
#    - target:
#        kind: Kustomization
#        name: podinfo
#      patch: |-
#        kind: Kustomization
#        metadata:
#          name: podinfo
#        spec:
#          patches:
#            - target:
#                kind: HorizontalPodAutoscaler
#                name: podinfo
#              patch: |-
#                apiVersion: autoscaling/v2
#                kind: HorizontalPodAutoscaler
#                metadata:
#                  name: podinfo
#                spec:
#                  minReplicas: 2
#                  maxReplicas: 8
