---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: elastic
  namespace: flux-system
spec:
  interval: 5m
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: ${namespace_name:=default}
  chart:
    spec:
      chart: eck-operator
#      version: '6.5.*'
      sourceRef:
        kind: HelmRepository
        name: elastic
      interval: 5m
  releaseName: elastic-operator
#  install:
#    remediation:
#      retries: 3
#  upgrade:
#    remediation:
#      retries: 3
#  test:
#    enable: true
##  driftDetection:
##    mode: enabled
##    ignore:
##    - paths: ["/spec/replicas"]
##      target:
##        kind: Deployment
##  values:
##    replicaCount: 2
