---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${issuer_name}
spec:
  acme:
    # Replace the email address with your own contact email
    email: bozho@symplectic.co.uk
    # The server is replaced in /clusters/production/infrastructure.yaml
    server: https://is-ca-server.symplectic.internal/acme/acme/directory
    skipTLSVerify: true # Should use the CA bundle instead.
    privateKeySecretRef:
      name: ${issuer_name}-cert-issuer-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: frontend
                namespace: ${namespace_name}
                kind: Gateway
