---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metallb
#  namespace: flux-system
spec:
  interval: 5m
  url: https://metallb.github.io/metallb

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
#  namespace: flux-system
spec:
#  targetNamespace: ${namespace_name:=default}
#  serviceAccountName: kustomize-controller
  chart:
    spec:
      chart: metallb
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: '0.14.8'
  interval: 5m
  values: {}
