#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: metallb-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/metallb/metallb
  ref:
    tag: v0.14.8
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: metallb-system
  sourceRef:
    kind: GitRepository
    name: metallb
  path: "./config/native"
  prune: true
  timeout: 1m
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.20.30.207/32
  - 10.20.30.208/32
  - 10.20.30.209/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system


