---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../_profiles/proxmox
resources:
  - metallb-config.yaml

#patchesStrategicMerge:
#patches:
##  - path: metallb-patches.yaml
#  - path: storage-patches.yaml
#    target:
#      kind: HelmRelease
#      name: local-static-provisioner
#      namespace: flux-system

