---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../_profiles/proxmox
resources:
  - metallb-config.yaml

patches:
  - target:
      kind: Kustomization
      name: podinfo-app
    patch: |-
      kind: Kustomization
      metadata:
        name: podinfo-app
      spec:
        patches:
          - target:
              kind: Kustomization
              name: podinfo
            patch: |-
              kind: Kustomization
              metadata:
                name: podinfo
              spec:
                patches:
                  - target:
                      kind: HorizontalPodAutoscaler
                      name: podinfo
                    patch: |-
                      apiVersion: autoscaling/v2
                      kind: HorizontalPodAutoscaler
                      metadata:
                        name: podinfo
                      spec:
                        minReplicas: 2
                        maxReplicas: 6

  - target:
      kind: Kustomization
      name: metallb
    patch: |-
      kind: Kustomization
      metadata:
        name: _
      spec:
        patches:
          - target:
              kind: IPAddressPool
            patch: |-
              apiVersion: metallb.io/v1beta1
              kind: IPAddressPool
              metadata:
                name: _
              spec:
                avoidBuggyIPs: true
                addresses:
                  - 10.10.10.207/32
                  - 10.10.10.208/32
                  - 10.10.10.209/32

##patchesStrategicMerge:
##  - metallb-patches.yaml
##  - storage-patches.yaml
#patches:
##  - target:
##      #version: v1beta1
##      #group: metallb.io
##      kind: IPAddressPool
##      name: example
###      namespace: metallb-system
##    patch: |-
##      apiVersion: metallb.io/v1beta1
##      kind: IPAddressPool
##      metadata:
##        name: example
##        namespace: metallb-system
##      spec:
##        addresses:
##          - 10.20.30.207/32
##          - 10.20.30.208/32
##          - 10.20.30.209/32
#
##  - path: metallb-patches.yaml
#  - target:
##      version: v1beta1
##      group: metallb.io
#      kind: IPAddressPool
#      name: example
##      namespace: metallb-system
#    patch: |-
#      - op: replace
#        path: /spec/addresses
#        value: |-
#          - 10.10.10.27/32
#          - 10.10.10.28/32
#          - 10.10.10.29/32
#
#
##  - path: storage-patches.yaml
##    target:
##      kind: HelmRelease
##      name: local-static-provisioner
##      namespace: flux-system
