---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-static-provisioner
  namespace: flux-system
spec:
  values:
    classes:
      - name: local-storage
        hostDir: /mnt/disks
        mountDir: /usr/share/elasticsearch/data
