---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: load-balancer
spec:
  addresses: []

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: load-balancer
spec:
  ipAddressPools:
    - load-balancer
