---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginx-gateway-fabric-crd
  namespace: flux-system
spec:
  interval: 5m
  ref:
    tag: v1.4.0
  url: https://github.com/nginxinc/nginx-gateway-fabric

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-gateway-fabric-crd
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: nginx-gateway-fabric-crd
  path: ./config/crd/gateway-api/standard
  prune: true
  retryInterval: 5m
  timeout: 3m0s
  wait: true
  postBuild: {}
