---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../_profiles/proxmox
resources: []

patches:
  - target:
      kind: Kustomization
      name: metallb
    patch: |-
      kind: Kustomization
      metadata:
        name: _
      spec:
        patches:
          - target:
              kind: IPAddressPool
            patch: |-
              apiVersion: metallb.io/v1beta1
              kind: IPAddressPool
              metadata:
                name: _
              spec:
                avoidBuggyIPs: true
                addresses:
                  - 10.20.30.207/32
                  - 10.20.30.208/32
                  - 10.20.30.209/32

#  - target:
#      kind: Kustomization
#      name: podinfo-app
#    patch: |-
#      kind: Kustomization
#      metadata:
#        name: podinfo-app
#      spec:
#        patches:
#          - target:
#              kind: Kustomization
#              name: podinfo
#            patch: |-
#              kind: Kustomization
#              metadata:
#                name: podinfo
#              spec:
#                patches:
#                  - target:
#                      kind: HorizontalPodAutoscaler
#                      name: podinfo
#                    patch: |-
#                      apiVersion: autoscaling/v2
#                      kind: HorizontalPodAutoscaler
#                      metadata:
#                        name: podinfo
#                      spec:
#                        minReplicas: 2
#                        maxReplicas: 6
#
