---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  elastic_instance_name: search
  gateway_name: frontend
  gateway_namespace: networking
  cluster_issuer_name: internal
