---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: elastic-operator
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
#  serviceAccountName: kustomize-controller
  path: ./platform/elastic-operator/_base
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: elastic-system

#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: elastic
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: elastic-operator
#  interval: 15m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
##  serviceAccountName: kustomize-controller
#  path: ./platform/elastic/_base
#  prune: true
#  wait: true
#  timeout: 5m
#  postBuild:
#    substitute:
#      elastic_name: foo
#      namespace_name: elastic
