---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
#  serviceAccountName: kustomize-controller
  path: ./infrastructure/gateway-api
  prune: true
  wait: true
  timeout: 5m

  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars

  patches:
    - target:
        kind: Gateway
        name: frontend
      patch: |-
        - op: add
          path: /metadata/annotations/cert-manager.io~1cluster-issuer
          value: ${cluster_issuer_name}
        - op: add
          path: /spec/listeners/-
          value:
            name: podinfo-https
            port: 443
            protocol: HTTPS
            hostname: podinfo.symplectic.internal
            allowedRoutes:
              namespaces:
                from: Selector
                selector:
                  matchLabels:
                    app.kubernetes.io/name: podinfo
            tls:
              mode: Terminate
              certificateRefs:
                - name: podinfo-cert
        - op: add
          path: /spec/listeners/-
          value:
            name: elastic-https
            port: 443
            protocol: HTTPS
            hostname: k8s-search.symplectic.internal
            allowedRoutes:
              namespaces:
                from: All
            tls:
              mode: Terminate
              certificateRefs:
                - name: elastic-cert