---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway
  namespace: flux-system
spec:
  dependsOn:
    - name: gateway-api
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
#  serviceAccountName: kustomize-controller
  path: ./infrastructure/gateway
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: networking
      gateway_name: frontend

  patches:
    - target:
        kind: Gateway
#        name: frontend
        name: ${gateway_name}
      patch: |-
        kind: Gateway
        metadata:
          name: _
        spec:
          listeners:
            - name: http2
              port: 80
              protocol: HTTP
              hostname: podinfo.symplectic.internal
              allowedRoutes:
                namespaces:
                  from: All
            - name: https
              port: 443
              protocol: HTTPS
              hostname: podinfo.symplectic.internal
              allowedRoutes:
                namespaces:
                  from: All
              tls:
                mode: Terminate
                certificateRefs:
                  - name: podinfo-cert

#  patches:
#    - target:
#        kind: Gateway
#        name: frontend
#      patch: |-
#        apiVersion: gateway.networking.k8s.io/v1
#        kind: Gateway
#        metadata:
#          name: _
#        spec:
#          listeners:
#            - name: http
#              port: 80
#              protocol: HTTP
#              hostname: podinfo.symplectic.internal
#              allowedRoutes:
#                namespaces:
#                  from: All
#            - name: https
#              port: 443
#              protocol: HTTPS
#              hostname: podinfo.symplectic.internal
#              allowedRoutes:
#                namespaces:
#                  from: All
#              tls:
#                mode: Terminate
#                certificateRefs:
#                  - name: podinfo-cert