---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  dependsOn:
    - name: gateway-api
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
#  serviceAccountName: kustomize-controller
  path: ./infrastructure/gateway
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: networking
      gateway_name: frontend
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars

  patches:
    - target:
        kind: Gateway
#        name: frontend
        name: \$${gateway_name}
      patch: |-
        - op: add
          path: /spec/listeners/-
          value:
            name: podinfo-https
            port: 443
            protocol: HTTPS
            hostname: podinfo.symplectic.internal
            allowedRoutes:
              namespaces:
                from: Selector
                selector:
                  matchLabels:
                    app.kubernetes.io/name: podinfo
            tls:
              mode: Terminate
              certificateRefs:
                - name: podinfo-cert
        - op: add
          path: /spec/listeners/-
          value:
            name: elastic-https
            port: 443
            protocol: HTTPS
            hostname: k8s-search.symplectic.internal
            allowedRoutes:
              namespaces:
                from: All
            tls:
              mode: Terminate
              certificateRefs:
                - name: elastic-cert


#      patch: |-
#        kind: Gateway
#        metadata:
#          name: _
#        spec:
#          listeners:
#            - name: http
#              port: 80
#              protocol: HTTP
#              allowedRoutes:
#                namespaces:
#                  from: All
#            - name: podinfo-https
#              port: 443
#              protocol: HTTPS
#              hostname: podinfo.symplectic.internal
#              allowedRoutes:
#                namespaces:
#                  from: Selector
#                  selector:
#                    matchLabels:
#                      app.kubernetes.io/name: podinfo
#              tls:
#                mode: Terminate
#                certificateRefs:
#                  - name: podinfo-cert
#            - name: elastic-https
#              port: 443
#              protocol: HTTPS
#              hostname: k8s-search.symplectic.internal
#              allowedRoutes:
#                namespaces:
#                  from: All
#              tls:
#                mode: Terminate
#                certificateRefs:
#                  - name: elastic-cert

#  patches:
#    - target:
#        kind: Gateway
#        name: frontend
#        #name: ${gateway_name}
#      patch: |-
#        kind: Gateway
#        metadata:
#          name: _
#        spec:
#          listeners:
#            - name: http
#              port: 80
#              protocol: HTTP
#              hostname: podinfo.symplectic.internal
#              allowedRoutes:
#                namespaces:
#                  from: Selector
#                  selector:
#                    matchLabels:
#                      app.kubernetes.io/name: podinfo
#            - name: https
#              port: 443
#              protocol: HTTPS
#              hostname: podinfo.symplectic.internal
#              allowedRoutes:
#                namespaces:
#                  from: Selector
#                  selector:
#                    matchLabels:
#                      app.kubernetes.io/name: podinfo
#              tls:
#                mode: Terminate
#                certificateRefs:
#                  - name: podinfo-cert
