---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - namespaces.yaml
  - gateway-api.yaml
  - nginx-gateway-fabric.yaml
  - gateway.yaml
  - cert-manager.yaml
  - elastic.yaml

patches:
  - target:
      kind: Gateway
      name: frontend
#        name: $${gateway_name}
    patch: |-
      kind: Gateway
      metadata:
        name: _
      spec:
        listeners:
          - name: http
            port: 80
            protocol: HTTP
            allowedRoutes:
              namespaces:
                from: All
          - name: podinfo-https
            port: 443
            protocol: HTTPS
            hostname: podinfo.symplectic.internal
            allowedRoutes:
              namespaces:
                from: Selector
                selector:
                  matchLabels:
                    app.kubernetes.io/name: podinfo
            tls:
              mode: Terminate
              certificateRefs:
                - name: podinfo-cert
          - name: elastic-https
            port: 443
            protocol: HTTPS
            hostname: k8s-search.symplectic.internal
            allowedRoutes:
              namespaces:
                from: All
            tls:
              mode: Terminate
              certificateRefs:
                - name: elastic-cert
