---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
#  serviceAccountName: kustomize-controller
  path: ./platform/nginx-gateway-fabric/_base
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: nginx

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: elastic
  namespace: nginx
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      port: 80
      protocol: HTTP

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: elastic
  namespace: nginx
spec:
  parentRefs:
    - name: elastic
      namespace: nginx
  hostnames:
    - "k8s-bozho.symplectic.internal"
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /es
      backendRefs:
        - name: foo-es-http
          namespace: elastic
          port: 9200
