---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ${instance_name}
spec:
  version: 8.15.3
  http:
    service:
      spec:
        type: ClusterIP
  nodeSets:
    - name: default
      count: 3
      config:
        node.store.allow_mmap: false
#    - name: masters
#      count: 3
#      config:
#        node.roles: ["master"]
#        xpack.ml.enabled: true
#        node.store.allow_mmap: false
#    - name: data
#      count: 3
#      config:
#        node.roles: ["data", "ingest", "ml", "transform"]
#        node.store.allow_mmap: false


---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: elastic3
spec:
  parentRefs:
    - name: ${gateway_name}
      namespace: ${gateway_namespace}
  hostnames: []
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /es
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: foo-es-http
          namespace: elastic
          port: 9200


---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: tls-upstream-elastic
spec:
  targetRefs:
    - kind: Service
      #name: ${instance_name}-es-http
      name: foo-es-http
      group: ""
  validation:
    caCertificateRefs:
      - kind: Secret
        name: foo-remote-ca
        group: ""
#    hostname: auth.example.com
