---
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-storage-config
  namespace: flux-system
data:
  values.yaml: |
    classes:
      - name: local-storage
        hostDir: /mnt/disks
        mountDir: /usr/share/elasticsearch/data
