---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic
spec:
  version: 8.15.3
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
  patches:
    - target:
        name: quickstart-es-http
        namespace: elastic
        kind: Service
      patch: |-
        apiVersion: v1
        kind: Service
        metadata:
          name: quickstart-es-http
          namespace: elastic
        spec:
          selector:
            common.k8s.elastic.co/type: elasticsearch
            elasticsearch.k8s.elastic.co/cluster-name: quickstart 
          type: LoadBalancer
