---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elastic
spec:
  version: 8.15.3
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
    - name: masters
      count: 3
      config:
        node.roles: ["master"]
        xpack.ml.enabled: true
        node.remote_cluster_client: false
        node.store.allow_mmap: false
    - name: data
      count: 10
      config:
        node.roles: ["data", "ingest", "ml", "transform"]
        node.remote_cluster_client: false
        node.store.allow_mmap: false
