---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
spec:
  interval: 5m
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
spec:
  interval: 5m
  path: ./kustomize
  prune: true
  retryInterval: 5m
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: ${namespace_name}
  timeout: 3m0s
  wait: true
  postBuild: {}


---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-redirect
spec:
  parentRefs:
    - name: ${gateway_name}
      namespace: ${gateway_namespace}
      sectionName: http
#  hostnames:
#    - podinfo.symplectic.internal
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: podinfo
spec:
  parentRefs:
    - name: ${gateway_name}
      namespace: ${gateway_namespace}
      sectionName: podinfo-https
  hostnames:
    - podinfo.symplectic.internal
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
#            value: /podinfo
#      filters:
#        - type: URLRewrite
#          urlRewrite:
#            path:
#              type: ReplacePrefixMatch
#              replacePrefixMatch: /
      backendRefs:
        - name: podinfo
          namespace: ${namespace_name}
          port: 9898

#        - name: ${instance_name}-es-https
#          namespace: ${namespace_name}
#          port: 9200
#  patches:
#    - target:
#        name: podinfo
##        namespace: podinfo33
#        kind: HorizontalPodAutoscaler
#      patch: |-
#        apiVersion: autoscaling/v2
#        kind: HorizontalPodAutoscaler
#        metadata:
#          name: podinfo
#        spec:
#          minReplicas: 2
#          maxReplicas: 5



#  patches:
#    - target:
#        name: podinfo
#        kind: HorizontalPodAutoscaler
#      patch: |-
#        apiVersion: autoscaling/v2
#        kind: HorizontalPodAutoscaler
#        metadata:
#          name: podinfo
#        spec:
#          minReplicas: 3
#    - target:
#        name:      podinfo
#        kind:      Service
#      patch: |-
#        apiVersion: v1
#        kind: Service
#        metadata:
#          name: podinfo
#        spec:
#          selector:
#            app: podinfo
#          type: LoadBalancer
#    - target:
#        name:      podinfo
#        kind:      Service
#      patch: |
#        - op: replace
#          path:  /spec/ports
#          value:
#            - name:       http
#              port:       8080
#              protocol:   TCP
#              targetPort: http
#            - name:       grpc
#              port:       8081
#              protocol:   TCP
#              targetPort: grpc
