---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner # indicates that this StorageClass does not support automatic provisioning
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sig-storage-local-static-provisioner
  namespace: infrastructure
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/sig-storage-local-static-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-static-provisioner
  namespace: infrastructure
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: local-static-provisioner
#      version: '6.5.*'
      sourceRef:
        kind: HelmRepository
        name: sig-storage-local-static-provisioner
      interval: 5m
  releaseName: local-static-provisioner
  values:
    classes:
      - name: local-storage
        hostDir: /mnt/disks
        mountDir: /usr/share/elasticsearch/data
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: elasticsearch-data
#spec:
#  capacity:
#    storage: 10Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: local-storage
#  local:
#    path: /var/opt/elastic
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - k8s-bozho-wrk-01
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: elasticsearch-data-2
#spec:
#  capacity:
#    storage: 10Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: local-storage
#  local:
#    path: /var/opt/elastic
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - k8s-bozho-wrk-02
