---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: nginx-gateway-fabric
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric
  ref:
    tag: 1.4.0

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginx-gateway-fabric-crd
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: v1.4.0
  url: https://github.com/nginxinc/nginx-gateway-fabric

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-gateway-fabric-crda
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./config/crd/gateway-api/standard
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
  name: nginx-gateway-fabric-crd
  targetNamespace: ${namespace_name:=default}
  timeout: 3m0s
  wait: true
  postBuild: {}

#---
#apiVersion: helm.toolkit.fluxcd.io/v2
#kind: HelmRelease
#metadata:
#  name: nginx-gateway-fabric
#  namespace: flux-system
#spec:
#  dependsOn:
#    - kind: Kustomization
#      name: nginx-gateway-fabric-crda
#  targetNamespace: ${namespace_name}
#  interval: 10m
#  releaseName: nginx-gateway-fabric
#  chartRef:
#    kind: OCIRepository
#    name: nginx-gateway-fabric
