---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: nginx-gateway-fabric
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric
  ref:
    tag: 1.4.0

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: flux-system
spec:
  targetNamespace: ${namespace_name}
  interval: 10m
  releaseName: nginx-gateway-fabric
  chartRef:
    kind: OCIRepository
    name: nginx-gateway-fabric
#  values:
#    service:
#      create: false
