---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: nginx-gateway-fabric
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric
  ref:
    tag: v1.4.0

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-gateway-fabric
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: nginx
  prune: true
  sourceRef:
    kind: OCIRepository
    name: nginx-gateway-fabric
  path: ./
