---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-app
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
#  serviceAccountName: kustomize-controller
  path: ./platform/podinfo/_base
  prune: true
  wait: true
  timeout: 5m
  postBuild:
    substitute:
      namespace_name: podinfo


  patches:
    - target:
        kind: Kustomization
        name: podinfo
      patch: |-
        kind: Kustomization
        metadata:
          name: podinfo
        spec:
          patches:
            - target:
                kind: HorizontalPodAutoscaler
                name: podinfo
                namespace: ${namespace_name}
              patch: |-
                apiVersion: autoscaling/v2
                kind: HorizontalPodAutoscaler
                metadata:
                  name: podinfo
                  namespace: ${namespace_name}
                spec:
                  minReplicas: 2
                  maxReplicas: 7


#  patches:
#    - target:
#        name: podinfo2
#        kind: HorizontalPodAutoscaler
#      patch: |-
#        apiVersion: autoscaling/v2
#        kind: HorizontalPodAutoscaler
#        metadata:
#          name: podinfo3
#        spec:
#          minReplicas: 3

#---
#apiVersion: source.toolkit.fluxcd.io/v1
#kind: GitRepository
#metadata:
#  name: podinfo
#  namespace: flux-system
#spec:
#  interval: 1m0s
#  ref:
#    branch: master
#  url: https://github.com/stefanprodan/podinfo
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: podinfo
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: podinfo
#  namespace: flux-system
#spec:
#  interval: 30m0s
#  path: ./kustomize
#  prune: true
#  retryInterval: 2m0s
#  sourceRef:
#    kind: GitRepository
#    name: podinfo
#  targetNamespace: podinfo
#  timeout: 3m0s
#  wait: true